# Generated by Django 3.2 on 2021-12-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_fun_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fun',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
